spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wanted-database.capfbot4gotl.ap-northeast-2.rds.amazonaws.com:3306/wanted_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: wanted_admin
    password: d4a1b2c3

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace